travis:
  secure:
    BINSTAR_TOKEN: KhuNorDT1FtIL6HRb3gfZWtCDm3bv7s/ZfrpJjiPJn1/toaYGt94jw9zUKWjcz09gmrMa9VFgz3kg1omBgS/7bIZcR7q0vhY+KNnr684W1w0G2Y5GFphAYQtWBm3llFwufql6JhOq5fN5qM0JimK93Lhi2zAStIeAQskKsSDqkotGfF54f7CHwoQI2uZ67Q5EL7Q9t3NipQujrS37XLiC3rXu7qMLR1EOZiixLRPr2yZ0wNFAuqFR/YAj+8uUz5P6PE1u49gZ9OHHg7DJhWv+QxTBtshGKkjRJIMAzKvasrq02lnbyYpG1NkMbIeb19Y0O1FMXCvZ32APZkuMttb+GZRatFoTKxC8tPGZRlBbkiZbr/Wcl7RmGWkOGN+gItxWOHuFydZgoSFqT2I8ylWdKHk393OsslMi8qLENkkeWXSGUYbX3DpVxXm0V3fkuWFGqxL86/R5LyFb+GWPI9yPV9fq4A9Wf5+Gtv+iX8OVNW3JqNeY0e/Icro68LcDs37kZvrMvXz9LdZZejgqkum5EsdUd/tIHlwwoLI3oonWx1s3zTOY5a/hjvAXGcVVHpqLkflBGzANu4EnCUzI2jYMPigMqFYXq48qIGd7QKvsQMzBOQq9pFu4lAG9iocLVZaZpstYmuN9z8dR9huddd8425gsYgDN1/t2VeIQvoTv5A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
